# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 469580af714760d58f2e946b873e11c7792d95cc510d18e0445d45576e753b944cf9a0567a28d34df8582e0caafe749037543bbb366c7e5ff914853e7ca8f949

test:
  secret_key_base: cd8c009e09faa13d6c4c5accef5c5a2e3d1f290937f2419c29d6fed6aa6a09610710e25c1d8d13e767f6ac6154f2d91b1420cad662d60ed83f5a21e068823470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
